# Generated by Django 4.1.5 on 2023-02-28 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twitterbot", "0003_alter_twitteraccountchecked_prediction"),
    ]

    operations = [
        migrations.CreateModel(
            name="TwitterAccountsCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("screen_name", models.CharField(max_length=100)),
                ("prediction", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="TwitterAccountChecked",
        ),
    ]
